chider/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,include
from django.contrib.auth import views as v
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/',v.LoginView.as_view(),name='login'),
    path('accounts/logout/',v.LogoutView.as_view(), name='logout'),
    path('',views.dashboard,name='dashboard'),
    path('screen',views.screen_page,name='home'),
    #dates
    path('calendar/',views.MyDateListView.as_view(),name='calendar'),
    path('new/',views.CreateMyDateView.as_view(),name='mydate_new'),
    path('date/<int:pk>',views.my_date_detail,name='date_detail'),
    path('date/<int:pk>/edit/',views.MyDateUpdateView.as_view(),name='date_edit'),
    path('date/<int:pk>/delete/',views.MyDateDeleteView.as_view(),name='date_delete'),
    path('date/<int:pk>/preview/',views.day_preview,name='preview'),
    #images
    path('images/',views.ImagesListView.as_view(),name='images'),
    path('import_images/',views.create_image_view,name='import_images'),
    path('image/<int:pk>/delete/',views.ImagesDeleteView.as_view(),name='image_delete'),
    #image to date
    path('date/<int:pk>/add_image/',views.create_day_image_view,name='add_image'),
    path('dayimage/<int:pk>/',views.DayImageDetailView.as_view(),name='dayimage_detail'),
    path('dayimage/<int:pk>/delete/',views.day_image_delete,name='dayimage_delete'),
    #mazel
    path('date/<int:pk>/add_mazel/',views.create_mazel_tov,name='add_mazel'),
    path('mazel/<int:pk>/',views.MazelTovDetailView.as_view(),name='mazel_detail'),
    path('mazel/<int:pk>/edit_mazel/',views.MazelTovUpdateView.as_view(),name='edit_mazel'),
    path('mazel/<int:pk>/delete/',views.mazel_tov_delete,name='mazel_delete'),
    #massage
    path('message/<int:pk>/edit_message/',views.MessageUpdateView.as_view(),name='edit_message'),
    #add
    path('add/',views.AddCreateView.as_view(),name='add'),
    #login
    path('accounts/profile/',views.LoginRedirect.as_view(),name='login_redirect'),
    path('/accounts/logout/',views.LogoutRedirect.as_view(),name='logout_redirect'),
]+ staticfiles_urlpatterns()




if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

luach/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.conf import settings

# date details
class MyDate(models.Model):
    english_date = models.DateField(auto_now=False)
    hebrew_date = models.CharField(max_length=20,unique=False)
    hebrew_year = models.CharField(max_length=10,unique=False)
    sof_zman_1 = models.TimeField(auto_now=False,blank=True,null=True)
    sof_zman_2 = models.TimeField(auto_now=False,blank=True,null=True)
    sof_zman_tefila = models.TimeField(auto_now=False,blank=True,null=True)
    
    def get_absolute_url(self ):
        return reverse('date_detail',kwargs={'pk':self.pk})

    def __str__(self):
        return ('%s %s' % (self.hebrew_date,self.hebrew_year))


# images
class Images(models.Model):
    image = models.ImageField(unique=False,upload_to='images/')

    def get_absolute_url(self):
        return reverse("image_detail",kwargs={'pk':pk})

    def __str__(self):
        return self.image.name
    



#mazel
class MazelTov(models.Model):
    date = models.ForeignKey('luach.MyDate',related_name='mazel',on_delete=models.CASCADE)
    mazel_tov = models.TextField(max_length=400)

    def get_absolute_url(self):
        return reverse("date_detail",kwargs={'pk':self.date.pk})

    def __str__(self):
        return str(self.mazel_tov)

#connect days and images together
class DayImage(models.Model):
    date = models.ForeignKey('luach.MyDate',related_name='day',on_delete=models.CASCADE)
    images = models.ForeignKey('luach.Images',related_name='images',on_delete=models.CASCADE)
    
    def get_absolute_url(self):
        return reverse("dayimage_detail",kwargs={'pk':self.pk})



class Message(models.Model):
    message = models.CharField(max_length=200,blank=True,null=True)

    def __str__(self):
        return self.message

class Add(models.Model):
    ad_image = models.ImageField(unique=False,upload_to='images/')

    def __str__(self):
        return self.ad_image.name
    

luach/forms.py
from django import forms
from luach.models import *

class MyDateForm(forms.ModelForm):
    class Meta:
        model = MyDate
        fields = '__all__'

        widgets = {
            'english_date':forms.DateInput({'type':'date'}),
            'sof_zman_1':forms.TimeInput({'type':'time'}),
            'sof_zman_2':forms.TimeInput({'type':'time'}),
            'sof_zman_tefila':forms.TimeInput({'type':'time'}),
        }




class DayImageForm(forms.ModelForm):

    keep_every_year = forms.BooleanField(required=False)
    keep_till = forms.IntegerField()

    class Meta:
        model = DayImage
        fields = ('images',)



class MazelTovForm(forms.ModelForm):

    keep_till = forms.IntegerField()

    class Meta:
        model = MazelTov
        fields = ('mazel_tov',)
        widgets = {'mazel_tov':forms.Textarea(attrs={'class':'form-control'})}

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'
        widgets = {'message':forms.Textarea(attrs={'class':'form-control'})}

class AddForm(forms.ModelForm):
    class Meta:
        model = Add
        fields = '__all__'

templates/luach/add_images.html
{% extends 'luach/base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">

        <label>Add Images</label>
        <br>
        <div class="row">
            <div class="col">
                <input type="file" multiple>
            </div>
            <div class="col">
            </div>
        </div>
        <button type="submit" id="saveBtn" class="btn btn-success mt-4">Save</button>
        <a class="btn btn-danger mt-4" href="{% url 'images' %}">cancel</a>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var files = []
        FilePond.registerPlugin(FilePondPluginFileValidateSize);
        FilePond.registerPlugin(FilePondPluginFileValidateType);
        FilePond.setOptions({
            allowMultiple:true,
            maxFiles:10,
            maxFileSize: '10MB'
        })
        const inputElement = document.querySelector('input[type="file"]');
        const pond = FilePond.create( inputElement, {
            acceptedFileTypes:['image/png', 'image/jpeg','image/jpg'],
            onaddfile: (err, fileItem) => {
                if (!err) {
                files.push(fileItem.file)
                }
                console.log(files)
            },
            onremovefile: (err, fileItem) => {
                const index = files.indexOf(fileItem.file)
                if (index > -1) {
                    files.splice(index, 1)
                }
                console.log(files)
            }
        } );

        var formData = new FormData();
        $(document).on('click', '#saveBtn', function(e) {
            formData.append('length', files.length)
            for (var i = 0; i < files.length; i++) {
                formData.append('images' + i, files[i])
            }
            formData.append('csrfmiddlewaretoken', '{{ csrf_token }}')

            $.ajax({
                type: 'POST',
                url: '{% url "import_images" %}',
                data: formData,
                cache: false,
                processData: false,
                contentType: false,
                enctype: 'multipart/form-data',
                success: function (){
                    //alert('The post has been created!')
                    window.location.href = "{% url 'images' %}";
                },
                error: function(xhr, errmsg, err) {
                    console.log(xhr.status + ":" + xhr.responseText)
                }
            })
        })
    })
</script>
{% endblock  %}

templates/luach/dashboard.html
{% extends 'luach/base.html' %}
{% load static %}
{% block content %}
<main>
    
    <div class="a">
        <div class="row">
            <div class="col">
                <a class="btn btn-primary btn-block" href="{% url 'home' %}">screen</a>
            </div>
            
        </div>
        <div class="row">
            <div class="jumbotron" style="border: 5px solid #7D7D7D; border-radius: 20px; padding: 20px; margin: 20px; margin-bottom: 5px; max-width: 1200px; background-color: #B8B8B8;">
                <div class="row text-center text-lg-left overflow-auto" style="max-height: 750px;">
                    {% for date in mydate %}
                        <div class="col-lg-3 col-md-4 col-6">
                            <div class="d-block mb-4 h-100">
                                <div class="card alert-dark mb-3" style="max-width: 18rem;">
                                    <div class="card-header"><h5><b>{{ date}}</b></h5></div>
                                    <div class="card-body">
                                        <h5 class="card-title">{{ date.english_date }}</h5>
                                        <a class="btn btn-success btn-sm" href="{% url 'date_detail' pk=date.pk %}">go</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    {% empty %}
                        <h2>Sorry, no dates in this list.</h2>    
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
    <div class="b">
        <div style="margin: 16px;margin-bottom: 0px;">
            
            <p class="h3 text-center" style="margin-right: 210px"><a class="btn btn-primary btn-sm" style="margin-right: 150px" href="{% url 'home' %}" target="_blank">preview</a><strong>showing now</strong></p>
        </div>
        <br>
        <div class="container">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                {% for p in dayimage %}
                    <li data-target="#carousel-example-1z" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.counter0 == 0 %} active {% endif %}"></li>
                {% empty %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                {% endfor %}
                </ol>
                <div class="carousel-inner b-b">
                {% for p in dayimage %}
                    <div class="carousel-item{% if forloop.counter0 == 0 %} active {% endif %}">
                        <img src="{{ p.images.image.url }}" class="d-block w-100 img-box" alt="...">
                    </div>
                {% empty %}
                    <div class="carousel-item active">
                        <img src="{% static 'images/Untitled-1.jpg' %}" class="d-block w-100 b-a" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/Untitled-2.jpg' %}" class="d-block w-100 b-a" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/Untitled-3.jpg' %}" class="d-block w-100 b-a" alt="...">
                    </div>
                {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <br>
        <div class="container">
            <div id="carouselExampleSlidesOnly" class="carousel slide slider-box" data-ride="carousel">
                
                <div class="carousel-inner">
                {% for i in daymazel %}
                    <div class="carousel-item{% if forloop.counter0 == 0 %} active {% endif %}">
                        <div class="text-box-big text-center text-c b-c">
                            <p><h1 class="text-center text-c">{{ i|safe|linebreaksbr }}</h1></p>
                        </div>
                    </div>
                {% empty %}
                    <div class="carousel-item active">
                        <div class="text-box-big b-c">
                            <p><h5 class="text-center text-c">ברכת מזל-טוב חמה ולבבית שלוחה אל תומכינו ידידינו הרה"ח ר' פלוני אלמוני שליט"א הרה"ח פלוני אלמוני שליט"א לרגל שמחת הבר מצווה לבנו-נכדו כמר פלוני אלמוני נ"י למזל טוב ובשעטומו"צ</h5></p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="text-box-big b-c">
                            <p><h5 class="text-center text-c">ברכת מזל-טוב חמה ולבבית שלוחה אל תומכינו ידידינו הרה"ח ר' פלוני אלמוני שליט"א הרה"ח פלוני אלמוני שליט"א לרגל שמחת הדגכ דגסע עכיחעיח ביעכעעחיע חיעיחע שדגע שגדע ובשעטומו"צ</h5></p> 
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="text-box-big b-c">
                            <p><h5 class="text-center text-c">ברכת מזל-טוב חמה ולבבית שלוחה אל תומכינו ידידינו הרה"ח ר' פלוני אלמוני שליט"א הרה"ח פלוני אלמוני שליט"א לרגל שמחת הבר מצווה לבנו-נכדו כמר פלוני אלמוני נ"י למזל טוב ובשעטומו"צ</h5></p>
                        </div>
                    </div>
                {% endfor %}
                </div>
                
            </div>
        </div>
    </div>
    <div class="c">
        
        <div class="message-box">
            <div class="message">
                <h2 class="text-center">message</h2>
            </div>
            <a class="btn btn-primary btn-sm c-a" href="{% url 'edit_message' pk=message.pk %}">edit</a>
            <p><h3 class="text-center">{{  message|safe|linebreaksbr }}</h3></p>
        </div>
        <div class="ad-box">
            <div class="ad">
                <h2 class="text-center">בחסות</h2>
            </div>
            <a class="btn btn-primary btn-sm c-a" href="{% url 'add' %}">edit</a>
            
            <img class="img-fluid c-b rounded mx-auto d-block img-thumbnail" src="{{add.ad_image.url}}" alt="hi">
            
        </div>
    </div>
</main>
{% endblock %}

templates/luach/dayimage_detail.html
{% extends 'luach/base.html' %}
{% block content %}
    <div class="container">
        <div class="jumbotron" style="padding-top:100px;">
            
            <h4>{{dayimage.date}}</h4>
            <img class="img-fluid img-thumbnail" src="{{dayimage.images.image.url}}" alt="">
            <a class="btn btn-danger" href="{% url 'image_delete' pk=dayimage.pk %}">delete</a>
           
        </div>
    </div>

{% endblock  %}

templates/luach/dayimage_form.html
{% extends 'luach/base.html' %}
{% block content %}

    <div class="jumbotron" style="margin-top:50px;">
        
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-10 overflow-auto" style="border: 5px solid #B8B8B8;padding:20px;max-height: 750px;">
                    <select class="image-picker" name="images" required="" id="id_images">
                        {% for p in form.images %}
                            {{p}}
                        {% endfor %}
                    </select>
                </div>
                <div class="col" style="border: 5px solid #B8B8B8;padding:20px;">
                    <hr>
                    <p>keep till {{form.keep_till}}</p>
                    <hr>
                    <p>keep for every year{{form.keep_every_year}}</p>
                    <hr>
                    <button type='submit' class='btn btn-success'>save</button>
                    
                    <a class="btn btn-danger" href="{% url 'date_detail' pk=date.pk %}">cancel</a>
                </div>            
            </div>
            
            
            
        </form>
        
    </div>

    <script>
        var option = document.getElementsByTagName("option");
       
        for(var i = 1; i < option.length; i++){
            option[i].setAttribute('data-img-src', 'https://storage.googleapis.com/luach-belz/'+option[i].innerHTML);
        }
        
        $('.image-picker').imagepicker({
            hide_select: true,
            show_label: true,
        });
    </script>
    <script>
        var text = document.getElementsByTagName('p');
        for(var a = 0; a < text.length; a++){
            var b = text[a].innerHTML.replace('images/','');
            text[a].innerHTML = (b);
        }
        
    </script>
    <script>
        var img = document.getElementsByClassName('image_picker_image');

        for(var a = 0; a < img.length; a++){
            img[a].style.maxWidth = "200px";
        }
        
        
        var checkbox = document.getElementById('id_keep_every_year');
        checkbox.style.margin = '5px';

    </script>
{% endblock  %}

templates/luach/login_redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <script>
        window.location.href = "{% url 'dashboard' %}";
    </script>
</body>
</html>

templates/luach/mazeltov_confirm_delete.html
{% extends 'luach/base.html' %}
{% block content %}
<div class="container jumbotron">
        <P>{{object}}</P>
        <h4>Are you sure you want to delete this mazel tov</h4>
        
        <a class='btn btn-danger' href="{% url 'mazel_delete' pk=p.pk %}">delete</a>
</div>
{% endblock %}

templates/luach/mazeltov_detail.html
{% extends 'luach/base.html' %}
{% block content %}
    <div class="container">
        <div class="jumbotron" style="padding-top:100px;">
            
            <p>{{mazeltov.mazel_tov}}</p>

            <a class="btn btn-warning" href="{% url 'edit_mazel' pk=mazeltov.pk %}">edit</a>
            <a class="btn btn-danger" href="{% url 'mazel_delete' pk=mazeltov.pk %}">delete</a>
        </div>
    </div>

{% endblock  %}

templates/luach/mazeltov_form.html
{% extends 'luach/base.html' %}
{{ form.media }}
{% block content %}
    <div class="container">
        <div class="jumbotron">
        <br>
        <br>
        <br>
            <form method="POST">
                {% csrf_token %}

                {{form.mazel_tov}}

                <br>
                <H6 class="text-danger">*Do not write more then 3 lines, it will cut of some of the words*</H6>
                <p>keep till {{form.keep_till}}</p>
                <button type='submit' class='btn btn-success'>save</button>




            </form>
        </div>
    </div>
    <!--<script>
        var editor = new MediumEditor('.editable');
    </script>-->
{% endblock  %}

templates/luach/message_form.html
{% extends 'luach/base.html' %}
{{ form.media }}
{% block content %}
    <div class="container">
        <div class="jumbotron">
        <br>
        <br>
        <br>
            <form method="POST">
                {% csrf_token %}
                
                {{form.message}}
                
                <br>
                <button type='submit' class='btn btn-success'>save</button>
                

                

            </form>
        </div>
    </div>
    <script>
        var editor = new MediumEditor('.editable');
    </script>
{% endblock  %}

templates/luach/mydate_confirm_delete.html
{% extends 'luach/base.html' %}
{% block content %}
<div class="container jumbotron">
    <form method="post">
        {% csrf_token %}
        <h4>Are you sure you want to delete {{object}}</h4>
        <a class="btn btn-success" href="{% url 'date_detail' pk=mydate.pk %}">cancel</a>
        <input type="submit" class="btn btn-danger" value="delete">
    </form>
</div>
{% endblock %}

templates/luach/mydate_detail_1.html
{% extends 'luach/base.html' %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="jumbotron jumbotron-fluid mx-auto">
            <table class="table table-sm">
                <tr>
                    <th class='text-center'><h1>{{mydate.hebrew_date}}</h1></th>
                    
                    
                </tr>
                <tr>
                    <td class='text-center'>{{mydate.english_date}}</td>
                    <td><a class="btn btn-success" href="{% url 'calendar' %}">back to calendar</a></td>
                    <td><a class='btn btn-warning' href="{% url 'date_edit' pk=mydate.pk %}">edit</a></td>
                    <td><a class='btn btn-danger' href="{% url 'date_delete' pk=mydate.pk %}">delete</a></td>
                    <td class="invisible">dddddddddddddddddddddddddddddddddddddddddddddd</td>
                </tr>
            </table>
            
            <div class="alert alert-secondary">
                <table class="table table-sm">
                    <tr>
                        <th></th>
                        <th class="text-center">סוף זמן קר''ש 1</th>
                        <th class="text-center">סוף זמן קר''ש 2</th>
                        <th class="text-center">סוף זמן תפילה</th>
                    </tr>
                    <tr>
                        <td></td>
                        <td class="text-center">{{mydate.sof_zman_1}}</td>
                        <td class="text-center">{{mydate.sof_zman_2}}</td>
                        <td class="text-center">{{mydate.sof_zman_tefila}}</td>
                    </tr>
                </table>
            </div>
            <br>
            
            
            
            <br>
        
            <div class="alert alert-secondary">
                <h2>Images</h2>
                <div class="row text-center text-lg-left">

                    {% for p in dayimage %}
                        <div class="col-lg-3 col-md-4 col-6">
                            <div class="d-block mb-4 h-100">
                                    <img class="img-fluid img-thumbnail" src="{{ p.images.image.url }}" alt="hi">
                                    <!-- Button trigger modal -->
                                    <a type="button" data-toggle="modal" data-target="#exampleModal">
                                    <span class="badge badge-danger">delete</span>
                                    </a>

                                    <!-- Modal -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">confirm delete</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Are you sure you want to delete this image?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-success btn-sm" data-dismiss="modal">Close</button>
                                                <a class="btn btn-danger btn-sm" href="{% url 'dayimage_delete' pk=p.pk %}">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    
                            </div>

                        </div>
                    {% empty %}
                        <h3>  There is no images linked to this day</h3>
                    {% endfor %}
                </div>
                <a class="btn btn-outline-primary btn-sm" href="{% url 'add_image' pk=mydate.pk %}">add image</a>
            </div>
            <div class="alert alert-secondary">
                <h2>Mazel Tov</h2>

                    {% for p in daymazel %}
                        <div class="card card-body">
                            <p>{{p}}</p>
                            <a href="{% url 'mazel_detail' pk=p.pk %}"><h4><span class="badge badge-success">details</span></h4></a>
                            
                        </div>
                        <br>
                    {% empty %}
                        <h3>There is no mazel tov on this day</h3>
                    {% endfor %}
                    
                <a class="btn btn-outline-primary btn-sm" href="{% url 'add_mazel' pk=mydate.pk %}">add mazel tov</a>
            </div>
        </div>
    </div>

        <!--<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel"  style="max-width:255px;">
            
            <ol class="carousel-indicators">
            {% for p in dayimage %}
                <li data-target="#carousel-example-1z" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.counter0 == 0 %} active {% endif %}"></li>
            {% endfor %}
            </ol>
            
            
            <div class="carousel-inner" role="listbox">
                    {% for p in dayimage %}
                    <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
                        <img class="d-block w-100" src="{{p.image.url}}" alt="First slide" style="max-width:255px;">
                    </div>
                    {% endfor %}
                    
                
                <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            
        </div>
        
        
    </div>
</div>-->
{% endblock  %}

templates/luach/mydate_form.html
{% extends 'luach/base.html' %}
{% block content %}
    <div class='container'>
        <div class="jumbotron">
            {% if not form.instance.pk %}
            <h1>add date</h1>
            {% else %}
            <h1>Edit date</h1>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type='submit' class='btn btn-success'>save</button>
                {% if not form.instance.pk %}
                <a class="btn btn-danger" href="{% url 'calendar' %}">cancel</a>
                {% else %}
                <a class="btn btn-danger" href="{% url 'date_detail' pk=mydate.pk %}">cancel</a>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock  %}

templates/luach/mydate_list.html
{% extends 'luach/base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div class="row text-center text-lg-left">
            {% for date in mydate %}
                <div class="col-lg-3 col-md-4 col-6">
                    <div class="d-block mb-4 h-100">
                        <div class="card bg-light mb-3" style="max-width: 18rem;">
                            <div class="card-header"><h5><b>{{ date.hebrew_date }}</b></h5></div>
                            <div class="card-body">
                                <h5 class="card-title">{{ date.english_date }}</h5>
                                <a class="btn btn-success btn-sm" href="{% url 'date_detail' pk=date.pk %}">go</a>
                            </div>
                        </div>
                    </div>
                </div>
                
            {% empty %}
                <h2>Sorry, no dates in this list.</h2>    
            {% endfor %}
        </div>
    </div>
</div>
{% endblock  %}